#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

function pid() {
    local pid=$( cat "${OPENSHIFT_DATA_DIR}xinetd.pid" )
    echo "${pid}"
    test -n "${pid}" && kill -0 "${pid}" &>/dev/null
}


if pid &>/dev/null; then
    warning "The server is already running."
    exit 0
fi

erb "${OPENSHIFT_REPO_DIR}xinetd.conf.erb" \
> "${OPENSHIFT_DATA_DIR}xinetd.conf"

xinetd \
    -pidfile "${OPENSHIFT_DATA_DIR}xinetd.pid" \
    -filelog "${OPENSHIFT_LOG_DIR}xinetd.log" \
    -f "${OPENSHIFT_DATA_DIR}xinetd.conf"
